code --install-extension ms-python.python
code --install-extension innerlee.nvidia-smi
code --install-extension ms-toolsai.jupyter
code --install-extension mutantdino.resourcemonitor
code --install-extension vahidk.tensorflow-snippets
code --install-extension sbsnippets.pytorch-snippets
code --install-extension sbsnippets.fastai-snippets
code --install-extension github.vscode-pull-request-github
code --install-extension editorconfig.editorconfig
code --install-extension mikestead.dotenv
